USE [master]
GO

/****** Object:  Database [dbAdresDefteri]    Script Date: 9.01.2018 21:29:41 ******/
CREATE DATABASE [dbAdresDefteri]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbAdresDefteri', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\dbAdresDefteri.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbAdresDefteri_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\dbAdresDefteri_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [dbAdresDefteri] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbAdresDefteri].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbAdresDefteri] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbAdresDefteri] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbAdresDefteri] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbAdresDefteri] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbAdresDefteri] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbAdresDefteri] SET  MULTI_USER 
GO

ALTER DATABASE [dbAdresDefteri] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbAdresDefteri] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbAdresDefteri] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbAdresDefteri] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbAdresDefteri] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbAdresDefteri] SET QUERY_STORE = OFF
GO

USE [dbAdresDefteri]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [dbAdresDefteri] SET  READ_WRITE 
GO


